import type { IconKey } from '@mdxeditor/editor';
import {
  AlignCenter,
  AlignLeft,
  AlignRight,
  Bold,
  Check,
  ChevronDown,
  Code,
  Columns3,
  Copy,
  ExternalLink,
  FileCode2,
  FileDiff,
  FileText,
  Highlighter,
  ImagePlus,
  Italic,
  Link,
  List,
  ListOrdered,
  ListTodo,
  MessageSquareWarning,
  Minus,
  MoreHorizontal,
  MoreVertical,
  PanelBottom,
  PanelLeft,
  PanelRight,
  PanelTop,
  Pencil,
  Redo2,
  Rows3,
  Settings,
  Strikethrough,
  Subscript,
  Superscript,
  Table,
  Trash2,
  Type,
  Underline,
  Undo2,
  Unlink,
  X,
  type LucideIcon,
} from 'lucide-react';

const iconComponents: Record<IconKey, LucideIcon> = {
  add_column: Columns3,
  add_photo: ImagePlus,
  add_row: Rows3,
  admonition: MessageSquareWarning,
  arrow_drop_down: ChevronDown,
  check: Check,
  close: X,
  code: Code,
  content_copy: Copy,
  delete_big: Trash2,
  delete_small: Trash2,
  difference: FileDiff,
  edit: Pencil,
  format_align_center: AlignCenter,
  format_align_left: AlignLeft,
  format_align_right: AlignRight,
  format_bold: Bold,
  format_highlight: Highlighter,
  format_italic: Italic,
  format_list_bulleted: List,
  format_list_checked: ListTodo,
  format_list_numbered: ListOrdered,
  format_underlined: Underline,
  frame_source: FileCode2,
  frontmatter: FileText,
  horizontal_rule: Minus,
  insert_col_left: PanelLeft,
  insert_col_right: PanelRight,
  insert_row_above: PanelTop,
  insert_row_below: PanelBottom,
  link: Link,
  link_off: Unlink,
  markdown: FileText,
  more_horiz: MoreHorizontal,
  more_vert: MoreVertical,
  open_in_new: ExternalLink,
  redo: Redo2,
  rich_text: Type,
  settings: Settings,
  strikeThrough: Strikethrough,
  subscript: Subscript,
  superscript: Superscript,
  table: Table,
  undo: Undo2,
};

export function richEditorIcon(name: IconKey) {
  const Icon = iconComponents[name];
  return <Icon aria-hidden="true" size={18} strokeWidth={2} />;
}
